site_name: ATLAS Product Suite
site_url: https://atlas.motionapplied.com/
edit_uri: edit/main/docs/
# repo_url: https://github.com/mat-docs/ATLAS.Site
docs_dir: 'docs'
site_description: '"Comprehensive technical documentation for Motion Applied ATLAS. Covering custom displays, data integration, APIs, and developer tools'

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: custom
    accent: custom
  logo: assets/swoosh/motion_applied_logo_white.svg
  favicon: assets/swoosh/motion_applied_logo.svg
  features:
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.prune 
    - navigation.indexes 
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - search.suggest
  icon:
    tag:
      prototype: fontawesome/solid/flask

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2025 Motion Applied Ltd.

nav:
  - Introduction:
    - Overview: introduction/index.md
    - Use Cases in Motorsport and Engineering: introduction/use-cases.md
    - Eco-System Overview: introduction/eco-system.md
  - Key Functionality:
    - Overview: key-functionality/index.md
    - Process:
      - SECU4:
        - Overview: key-functionality/process/secu4/index.md 
        - Virtual Parameter Service: key-functionality/process/secu4/vps.md
        - Bridge Service: key-functionality/process/secu4/bridge-service.md
        - Parquet Support: key-functionality/process/secu4/parquet.md
    - Visualisation: 
      - Overview: key-functionality/visualise/atlas/index.md
      - ATLAS: 
        - System Operation: 
          - Mouse Actions: key-functionality/visualise/atlas/system-operation/mouse.md
          - Keyboard Shortcuts: key-functionality/visualise/atlas/system-operation/keyboard.md
        - Handling Data:
          - Recorders: 
            # - USB Recorder: key-functionality/visualise/atlas/handling-data/recorders/usb-logger.md
            - NASCAR Telemetry Recorder: key-functionality/visualise/atlas/handling-data/recorders/nascar-telemetry-recorder.md
            - Data Server Telemetry Recorder: key-functionality/visualise/atlas/handling-data/recorders/data-server.md
            - File Telemetry Recorder: key-functionality/visualise/atlas/handling-data/recorders/file-telemetry.md
            - Ethernet File Telemetry: key-functionality/visualise/atlas/handling-data/recorders/ethernet-file.md
            - Ethernet Multi Session Offload: key-functionality/visualise/atlas/handling-data/recorders/ethernet-mso.md
            - Ethernet Offload: key-functionality/visualise/atlas/handling-data/recorders/ethernet-offload.md
            - Stream Recorder: key-functionality/visualise/atlas/handling-data/recorders/stream-recorder.md
          - Sessions:
            - Overview: key-functionality/visualise/atlas/handling-data/sessions/index.md
            - Session Browser: key-functionality/visualise/atlas/handling-data/sessions/browser.md
            - Loading Sessions: key-functionality/visualise/atlas/handling-data/sessions/loading-sessions.md
            - Changing Properties: key-functionality/visualise/atlas/handling-data/sessions/properties.md
          - Laps and Markers:
            - Markers: key-functionality/visualise/atlas/handling-data/laps-markers/markers.md
            - Laps: key-functionality/visualise/atlas/handling-data/laps-markers/laps.md
        - Functions: 
          - Overview: key-functionality/visualise/atlas/functions/index.md
          - Processing: key-functionality/visualise/atlas/functions/processing.md
          - Using DLLs: key-functionality/visualise/atlas/functions/using-dlls.md
        - Displays: 
          - Scatterplot: key-functionality/visualise/atlas/displays/scatterplot.md
  - Getting Started: 
    - Quick Start Guide: getting-started/quick-start.md
    - Security: getting-started/security.md
    - System Requirements: getting-started/sysreqs.md
  - Developer Resources:
    - Overview: developer-resources/index.md
    - SECU4: 
      - Stream API: 
        - Overview:                   developer-resources/secu4/stream_api/index.md
        - Stream API Client:          developer-resources/secu4/stream_api/stream_client.md
        - Stream API Server:          developer-resources/secu4/stream_api/stream_server.md
        - Key Generator Service:      developer-resources/secu4/stream_api/key_generator.md
        - Sample Code:                https://github.com/mat-docs/MA.Streaming.Api.UsageSample
        - Protocol Documentation: developer-resources/secu4/docs.md
      - Bridge Service: 
        - Overview: developer-resources/secu4/bridge_service/index.md
      - Configuration API: 
        - Overview: developer-resources/secu4/configuration_api/index.md
        - Protobuf:                 https://github.com/mat-docs/System.Monitor.Configuration.API.Client.Sample/tree/main/Protos
        - Example:                  https://github.com/mat-docs/System.Monitor.Configuration.API.Client.Sample/tree/main
        - Protocol Documentation:   developer-resources/secu4/configuration_api/docs.md
      - Support Library: 
        - Overview: developer-resources/secu4/support_library/index.md
    - ATLAS: 
      - Overview: developer-resources/atlas/index.md
      - Nuget: 
        - Overview: developer-resources/atlas/nuget/index.md
        - Setup Guide: developer-resources/atlas/nuget/setup.md
      - SQLRace API: 
        - Overview: developer-resources/atlas/sql-race/index.md
        - Parameter Data Access: developer-resources/atlas/sql-race/parameter-data-access.md
      - Display API: 
        - Introduction: developer-resources/atlas/display-api/index.md
        - Getting Started: developer-resources/atlas/display-api/overview.md
        - Tutorials:
          -  developer-resources/atlas/display-api/devguide/createfromscratch.md
          -  developer-resources/atlas/display-api/devguide/diagnostic.md
          -  developer-resources/atlas/display-api/devguide/numericcompare.md
          -  developer-resources/atlas/display-api/devguide/graphical.md
          -  developer-resources/atlas/display-api/devguide/gauge.md
          -  developer-resources/atlas/display-api/devguide/deploymentscript.md
          -  developer-resources/atlas/display-api/devguide/displaypluginlibrary.md
        - Enhancing Displays:
          -  developer-resources/atlas/display-api/factoriesandservices.md
          -  developer-resources/atlas/display-api/initialization.md
          -  developer-resources/atlas/display-api/displayprops.md
          -  developer-resources/atlas/display-api/sessions.md
          -  developer-resources/atlas/display-api/timebasecursor.md
          -  developer-resources/atlas/display-api/parameters.md
          -  developer-resources/atlas/display-api/data.md
          -  developer-resources/atlas/display-api/goodcitizenship.md
        - Further Information:
            -  developer-resources/atlas/display-api/coreapi.md
            -  developer-resources/atlas/display-api/limitations.md
            -  developer-resources/atlas/display-api/mvvm.md
            -  developer-resources/atlas/display-api/prerequisites.md
        - API Reference: "https://mat-docs.github.io/Atlas.DisplayAPI.Documentation/index.html"
    - RTA: 
      - Introduction: developer-resources/rta/worked-guide/index.md
      - Services Reference:
        - Overview:                   developer-resources/rta/services/index.md
        - Server:
          - README:                   developer-resources/rta/services/rta-server/README.md
          - gRPC APIs:                developer-resources/rta/services/rta-server/grpc.md
        - Session Service:    
          - README:                   developer-resources/rta/services/rta-sessionsvc/README.md
          - gRPC API:                 developer-resources/rta/services/rta-sessionsvc/grpc.md
        - Config Service:   
          - README:                   developer-resources/rta/services/rta-configsvc/README.md
          - gRPC API:                 developer-resources/rta/services/rta-configsvc/grpc.md
        - Data Service:   
          - README:                   developer-resources/rta/services/rta-datasvc/README.md
          - gRPC API:                 developer-resources/rta/services/rta-datasvc/grpc.md
        - Gateway Service:    
          - README:                   developer-resources/rta/services/rta-gatewaysvc/README.md
        - Stream Service:   
          - README:                   developer-resources/rta/services/rta-streamsvc/README.md
        - Schema Mapping Service:
          - README:                   developer-resources/rta/services/rta-schemamappingsvc/README.md
          - gRPC API:                 developer-resources/rta/services/rta-schemamappingsvc/grpc.md
        - Influx Data Service:
          - README:                   developer-resources/rta/services/rta-influxdatasvc/README.md
      - Worked Guide:
        - Tutorials:
          - Prerequisites:            developer-resources/rta/worked-guide/tutorials/prerequisites.md
          - '01: Quick-Start':
            - Walkthrough:            developer-resources/rta/worked-guide/tutorials/quick-start/index.md
            - Review:                 developer-resources/rta/worked-guide/tutorials/quick-start/review.md
          - '02: Microservices':
            - Walkthrough:            developer-resources/rta/worked-guide/tutorials/microservices/index.md
            - Review:                 developer-resources/rta/worked-guide/tutorials/microservices/review.md
          - '03: InfluxDB Data Adapter':
            - Walkthrough:            developer-resources/rta/worked-guide/tutorials/influx/index.md
            - Review:                 developer-resources/rta/worked-guide/tutorials/influx/review.md
          - '04: Live Streaming':
            - Walkthrough:            developer-resources/rta/worked-guide/tutorials/live/index.md
            - Review:                 developer-resources/rta/worked-guide/tutorials/live/review.md
          - '05: Custom Data Adapter':
            - Walkthrough:            developer-resources/rta/worked-guide/tutorials/data-adapter/index.md
            - Review:                 developer-resources/rta/worked-guide/tutorials/data-adapter/review.md
        - Working with Sessions:
          - Session Basics:           developer-resources/rta/worked-guide/sessions/index.md
          - Session Model:            developer-resources/rta/worked-guide/sessions/model.md
          - Session Service:          developer-resources/rta/worked-guide/sessions/session-service.md
          - Relationships:            developer-resources/rta/worked-guide/sessions/relationships.md
          - Listing and Queries:      developer-resources/rta/worked-guide/sessions/queries.md
          - Folders:                  developer-resources/rta/worked-guide/sessions/folders.md
          - Session Metamodel:        developer-resources/rta/worked-guide/sessions/metamodel.md
          - Data Bindings:            developer-resources/rta/worked-guide/sessions/data-bindings.md
        - Working with Configuration:
          - Configuration Basics:     developer-resources/rta/worked-guide/configuration/index.md
          - Channels and Parameters:  developer-resources/rta/worked-guide/configuration/channels-parameters.md
          - Parameter Groups (tree):  developer-resources/rta/worked-guide/configuration/parameter-groups.md
          - Conversions:              developer-resources/rta/worked-guide/configuration/conversions.md
          - Event Definitions:        developer-resources/rta/worked-guide/configuration/event-defs.md
          - Serializing JSON/FFC:     developer-resources/rta/worked-guide/configuration/serializing.md
          - Publishing to the Config Service: developer-resources/rta/worked-guide/configuration/publishing.md
        - Working with Data:
          - Data Basics:              developer-resources/rta/worked-guide/data/index.md
          - Schema Mappings:          developer-resources/rta/worked-guide/data/schema-mappings.md
          - Chunks:                   developer-resources/rta/worked-guide/data/chunks.md
        - Live-Streaming Data:
          - Live-Streaming Basics:    developer-resources/rta/worked-guide/live/index.md
          - WebSocket Protocol:       developer-resources/rta/worked-guide/live/websockets.md
          - Streaming to Redis:       developer-resources/rta/worked-guide/live/redis.md
        - Protobuf Schemas:
          - Overview:                 developer-resources/rta/worked-guide/protobuf/index.md
          - model_data.proto:         developer-resources/rta/worked-guide/protobuf/model_data.md
          - net_chunks.proto:         developer-resources/rta/worked-guide/protobuf/net_chunks.md
          - net_stream.proto:         developer-resources/rta/worked-guide/protobuf/net_stream.md
      - Useful Utilities:           
        - Overview: developer-resources/rta/worked-guide/utilities.md
        - Downloads: developer-resources/rta/downloads.md
        - REST API: 
          - Overview: developer-resources/rta/api/index.md
      - FAQ: developer-resources/rta/worked-guide/faq.md
  - Extensibility:
    - APIs: 
      - Overview: extending-atlas/apis/index.md
    - Streaming Architecture: 
          - Overview: extending-atlas/open_streaming_architecture/index.md
    - Remote Telemetry Architecture (RTA): 
        - Overview: extending-atlas/rta/index.md
        - Architectures: extending-atlas/rta/introduction/architectures.md
        - Data Services: extending-atlas/rta/introduction/data-services.md
        - Sessions: extending-atlas/rta/introduction/sessions.md
        - Configuration: extending-atlas/rta/introduction/configuration.md
  - News and Release Notes: blog/index.md
  - Downloads: https://portal.motionapplied.com/
  - Support: 
    - Troubleshooting: 
      - Profiling: key-functionality/visualise/atlas/troubleshooting/profiling.md
    - Zendesk: https://mclarenappliedtechnologies.zendesk.com/hc/en-us


markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - toc:
      permalink: "#"
  - meta
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mat-docs/
    - icon: fontawesome/brands/linkedin
      link: https://uk.linkedin.com/company/motionapplied
    - icon: fontawesome/solid/paper-plane
      link: mailto:sales@mclarenapplied.com
  tags:
    prototype: prototype

plugins:
  - blog
  - search
  - tags