site_name: ATLAS Documentation
site_url: https://atlas.mclarenapplied.com/
edit_uri: edit/main/docs/
repo_url: https://github.com/mat-docs/ATLAS.Site
docs_dir: 'docs'
site_description: '"Comprehensive technical documentation for McLaren ATLAS. Covering custom displays, data integration, APIs, and developer tools'

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: 'orange'
    accent: 'blue'
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico
  features:
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.prune 
    - navigation.indexes 
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2025 Motion Applied Ltd.

nav:
  - Getting Started: 
    - Introduction: getting-started/introduction.md
    - Quick Start Guide: getting-started/quick-start.md
    - Product Variants and Packages: getting-started/product-variants.md
    - Core Concepts: getting-started/core-concepts.md
    - Security: getting-started/security.md
    - Support: https://mclarenappliedtechnologies.zendesk.com/hc/en-us
  - Distribute & Capture: 
    - System Monitor: 
      - Projects: distribute-and-capture/system-monitor/projects.md 
      - Configuring the ECU: distribute-and-capture/system-monitor/configuring-ecu.md
      - Configuring the Logger: distribute-and-capture/system-monitor/configuring-logger.md
      - Integrating with ATLAS: distribute-and-capture/system-monitor/integrating-with-atlas.md
    - ATLAS Data Server: 
      - Recorders: distribute-and-capture/ads/recorders.md
      - Integrating with System Monitor: distribute-and-capture/ads/system-monitor.md
      - Remote Data Server: distribute-and-capture/ads/rds.md
  - Process:
    - vTAG: 
      - Overview: process/vtag/introduction.md
      - Integrating with ADS: process/vtag/integrating-with-ads.md
      - Running Simulink Models: process/vtag/simulink.md
    - SECU4: 
      - Virtual Parameter Service: process/secu4/vps.md
      - Bridge Service: process/secu4/bridge-service.md
      - Parquet Support: process/secu4/parquet.md
  - Store:
    - SQLRace Server: store/sqlrace/index.md
  - Visualise: 
    - ATLAS: 
      - Overview: visualise/atlas/overview.md
      - Fundamentals: visualise/atlas/fundamentals.md
      - Working with Data: visualise/atlas/working-with-data.md
      - Visualisation Tools: visualise/atlas/visualisation-tools.md
      - Troubleshooting: visualise/atlas/troubleshooting.md
  - Developer Resources:
    - System Monitor: 
      - COM API: developer-resources/system-monitor/automation.md
    - vTAG: developer-resources/vtag/index.md
    - SECU4: 
      - Stream API: developer-resources/secu4/stream-api.md
      - Bridge Service: developer-resources/secu4/bridge-service.md
      - Configuration API: developer-resources/secu4/configuration-api.md
      - Support Library: developer-resources/secu4/support-library.md
    - ATLAS: 
      - SQLRace API: developer-resources/atlas/sqlrace.md
      - Display API: 
        - Overview: developer-resources/atlas/display-api/index.md
        - Tutorials:
          -  developer-resources/atlas/devguide/createfromscratch.md
          -  developer-resources/atlas/devguide/diagnostic.md
          -  developer-resources/atlas/devguide/numericcompare.md
          -  developer-resources/atlas/devguide/graphical.md
          -  developer-resources/atlas/devguide/gauge.md
          -  developer-resources/atlas/devguide/deploymentscript.md
          -  developer-resources/atlas/devguide/displaypluginlibrary.md
        - Enhancing Displays:
          -  developer-resources/atlas/display-api/factoriesandservices.md
          -  developer-resources/atlas/display-api/initialization.md
          -  developer-resources/atlas/display-api/displayprops.md
          -  developer-resources/atlas/display-api/sessions.md
          -  developer-resources/atlas/display-api/timebasecursor.md
          -  developer-resources/atlas/display-api/parameters.md
          -  developer-resources/atlas/display-api/data.md
          -  developer-resources/atlas/display-api/goodcitizenship.md
        - Further Information:
            -  developer-resources/atlas/display-api/coreapi.md
            -  developer-resources/atlas/display-api/limitations.md
        - API Reference: "https://mat-docs.github.io/Atlas.DisplayAPI.Documentation/index.html"
      - Automation API: developer-resources/atlas/automation.md
    - RTA: 
      - REST API: developer-resources/rta/rest-api.md
  - Extending ATLAS:
    - SECU4: 
      - Open Streaming Architecture:
          - Overview:                     extending-atlas/secu4/open_streaming_architecture/index.md
          - Bridge Service:               extending-atlas/secu4/open_streaming_architecture/bridge_service/index.md
          - Stream API:
            - Overview:                   extending-atlas/secu4/open_streaming_architecture/stream_api/index.md
            - Stream API Client:          extending-atlas/secu4/open_streaming_architecture/stream_api/stream_client.md
            - Stream API Server:          extending-atlas/secu4/open_streaming_architecture/stream_api/stream_server.md
            - Key Generator Service:      extending-atlas/secu4/open_streaming_architecture/stream_api/key_generator.md
            - Sample Code:                https://github.com/mat-docs/MA.Streaming.Api.UsageSample
          - Suppport Library:             extending-atlas/secu4/open_streaming_architecture/support_library/index.md
          - Protocol Documentation:       extending-atlas/secu4/open_streaming_architecture/docs.md
          - Open Source Repositories:     https://github.com/Software-Products
    - RTA: 
      - Introduction:
        - Overview: extending-atlas/rta/index.md
        - Architectures: extending-atlas/rta/introduction/architectures.md
        - Data Services: extending-atlas/rta/introduction/data-services.md
        - Sessions: extending-atlas/rta/introduction/sessions.md
        - Configuration: extending-atlas/rta/introduction/configuration.md
  - News: news/index.md
  - Downloads: https://portal.mclarenapplied.com/


markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - toc:
      permalink: "#"
  - meta
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mat-docs/ATLAS.Site
    - icon: fontawesome/brands/linkedin
      link: https://uk.linkedin.com/company/motionapplied
    - icon: fontawesome/solid/paper-plane
      link: mailto:sales@mclarenapplied.com