[build]
command = "mkdocs build"
publish = "site"

[[headers]]
  for = "*.min.js"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[[headers]]
  for = "*.min.css"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[[headers]]
  for = "assets/swoosh/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[[headers]]
  for = "assets/swoosh-black/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[[headers]]
  for = "sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "search/search_index.json"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "assets/images/favicon.png"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[redirects]]
  from = "https://atlas.mclarenapplied.com/*"
  to = "https://atlas.motionapplied.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/key-functionality/visualise/atlas/*"
  to = "/key-functionality/analyse/viewer/:splat"
  status = 301

[[redirects]]
  from = "/key-functionality/store/ads/*"
  to = "/key-functionality/stream/ads/:splat"
  status = 301

[[redirects]]
  from = "/extending-atlas/apis/*"
  to = "/key-functionality/integrate/apis/:splat"
  status = 301

[[redirects]]
  from = "/extending-atlas/rta/*"
  to = "/key-functionality/integrate/rta/:splat"
  status = 301

[[redirects]]
  from = "/extending-atlas/open_streaming_architecture/*"
  to = "/key-functionality/stream/open_streaming_architecture/:splat"
  status = 301

[[redirects]]
  from = "/key-functionality/process/vtag/*"
  to = "/key-functionality/enrich/vtag/:splat"
  status = 301

[[redirects]]
  from = "/key-functionality/process/secu4/*"
  to = "/developer-resources/secu4/:splat"
  status = 301

[[redirects]]
  from = "/developer-resources/secu4/configuration_api/*"
  to = "/developer-resources/system-monitor/configuration_api/:splat"
  status = 301